# Generated by Django 5.2.4 on 2025-07-19 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_temperature', models.FloatField(verbose_name='体温')),
                ('blood_sugar_level', models.IntegerField(verbose_name='血糖値')),
                ('spo2_level', models.FloatField(verbose_name='酸素飽和度')),
                ('blood_pressure_high', models.IntegerField(verbose_name='最高血圧')),
                ('blood_pressure_low', models.IntegerField(verbose_name='最低血圧')),
                ('checked_up_at', models.DateTimeField(verbose_name='測定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
