# Generated by Django 5.2.4 on 2025-08-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='body_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='体温'),
        ),
    ]
