# Generated by Django 5.2.4 on 2025-08-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_alter_vital_body_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='blood_pressure_high',
            field=models.IntegerField(blank=True, null=True, verbose_name='最高血圧'),
        ),
        migrations.AlterField(
            model_name='vital',
            name='blood_pressure_low',
            field=models.IntegerField(blank=True, null=True, verbose_name='最低血圧'),
        ),
        migrations.AlterField(
            model_name='vital',
            name='blood_sugar_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='血糖値'),
        ),
        migrations.AlterField(
            model_name='vital',
            name='spo2_level',
            field=models.FloatField(blank=True, null=True, verbose_name='酸素飽和度'),
        ),
    ]
