# Generated by Django 5.2.4 on 2025-10-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0003_alter_vital_blood_pressure_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='心拍数'),
        ),
    ]
