# Generated by Django 5.2.4 on 2025-10-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0004_vital_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='spo2_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='酸素飽和度'),
        ),
    ]
